var mapperfields =  
[
     {fieldName:"bankName", newFieldName: "au_bankNames"},
     {fieldName:"subAccount", newFieldName: "au_subAccount"},
     {fieldName:"recipientId", newFieldName: "au_recipientId"},
     {fieldName:"paymentValueDate", newFieldName: "au_paymentValueDate"},
     {fieldName:"paymentDate", newFieldName: "au_paymentDate"},
     {fieldName:"paymentMethod", newFieldName: "au_paymentMethod"},
     {fieldName:"paymentStatus", newFieldName: "au_paymentStatus"},
     {fieldName:"paymentApproved", newFieldName: "au_paymentApproved"},
     {fieldName:"paymentCurrency", newFieldName: "au_paymentCurrency"},
     {fieldName:"paymentAmount", newFieldName: "au_paymentAmount"},
     {fieldName:"accountId", newFieldName: "au_accountId"},
     {fieldName:"bankAccountCurrency", newFieldName: "au_bankAccountCurrency"}, 
     {fieldName:"bankAccountName", newFieldName: "au_bankAccountName"}, 
     {fieldName:"bankAccountCountry", newFieldName:"au_bankAccountCountry"},
     {fieldName:"swiftBicCode", newFieldName: "au_swiftBicCode"},
     {fieldName:"iban", newFieldName: "au_iban"},
     {fieldName:"branchCode", newFieldName:"au_branchCode"},
     {fieldName:"accountNumber", newFieldName:"au_accountNumber"},
     {fieldName:"recipientDetails", newFieldName:"au_recipientDetails"},
     {fieldName:"id", newFieldName:"au_id"},
     {fieldName:"type", newFieldName:"au_type"},
     {fieldName:"attributes", newFieldName:"au_attributes"},
     {fieldName:"data", newFieldName:"au_data"},
     {fieldName:"paymentReference", newFieldName:"au_paymentReference"},
     {fieldName:"clientReference", newFieldName:"au_clientReference"},
     {fieldName:"batchReference", newFieldName:"au_batchReference"},
     {fieldName:"ultimatePayer", newFieldName:"au_ultimatePayer"},
     {fieldName:"ultimatePayerAccountId", newFieldName:"au_ultimatePayerAccountId"},
     {fieldName:"ultimatePayerName", newFieldName:"au_ultimatePayerName"},
     {fieldName:"ultimatePayerAddressLine1", newFieldName:"au_ultimatePayerAddressLine1"},
     {fieldName:"ultimatePayerAddressLine2", newFieldName:"au_ultimatePayerAddressLine2"},
     {fieldName:"ultimatePayerAddressLine3", newFieldName:"au_ultimatePayerAddressLine3"},
     {fieldName:"ultimatePayerCountry", newFieldName:"au_ultimatePayerCountry"},
     {fieldName:"createdAt", newFieldName:"au_createdAt"},
     {fieldName:"createdBy", newFieldName:"au_createdBy"},
     {fieldName:"updatedAt", newFieldName:"au_updatedAt"},
     {fieldName:"supportingDocumentsRequired", newFieldName:"au_supportingDocumentsRequired"},


     {fieldName:"meta", newFieldName:"au_meta"},
     {fieldName:"links", newFieldName:"au_links"},
     {fieldName:"first", newFieldName:"au_first"},
     {fieldName:"last", newFieldName:"au_last"},
     {fieldName:"prev", newFieldName:"au_prev"},
     {fieldName:"next", newFieldName:"au_next"},
     {fieldName:"self", newFieldName:"au_self"},
     {fieldName:"jsonapi", newFieldName:"au_jsonapi"},
     {fieldName:"version", newFieldName:"au_version"},
     {fieldName:"totalPages", newFieldName:"au_totalPages"},


]
module.exports = mapperfields;